Repository debionetwork/debio-genetic-analyst-ui, pull requests merged in 2022-03, with the labels that each got.

#1 [DBIO-1980 DBIO-1981] ci: setup github workflows
  .dockerignore
  .github/workflows/deployer.yml
  .github/workflows/dev-tmp.yml
  .github/workflows/tester.yml
  .maintain/docker/Dockerfile
  .maintain/docker/docker-compose.yml
  .maintain/docker/nginx/conf.d/default.conf
  .maintain/docker/nginx/nginx.conf
  package-lock.json
Labels: CI

#4 fix: Add code improvement
  src/views/Dashboard/GeneticAnalyst/Orders/Details.vue
Labels: Improvement

#5 fix: recaptcha.
  src/views/LandingPage/GenerateAccount/SetPassword.vue
  src/views/LandingPage/SignIn/ChangePassword.vue
Labels: Fix

#8 fix: Mismatch route and remove trailing spaces
  src/common/components/NavigationDrawer.vue
  src/common/lib/route-guard.js
  src/views/LandingPage/GenerateAccount/RegistrationSuccessful.vue
  src/views/LandingPage/SignIn/index.vue
  src/views/NotFound.vue
Labels: Fix, Improvement

#7 refactor: Update several ui/ux experiences
  src/views/Dashboard/GeneticAnalyst/Orders/Details.vue
Labels: Fix, Improvement, refactor

#6 [DBIO-1928] feat: Verification status (Dynamic) #358
  src/store/substrate/index.js
  src/views/Dashboard/GeneticAnalyst/Home/index.vue
Labels: Feature

#9 [DBIO-1929] tests: Update GA unit testing
  src/common/lib/pinata/index.js
  src/views/Dashboard/GeneticAnalyst/Home/index.vue
  src/views/Dashboard/GeneticAnalyst/Orders/Details.vue
  tests/unit/views/Dashboard/GeneticAnalyst/Home/index.spec.js
Labels: Fix, tests

#12 ci: optimize deployment resource request
  .github/workflows/deployer.yml
Labels: CI

#14 [DBIO-2171, DBIO-2172] feat: create ga service list and unit test
  src/common/lib/polkadot-provider/command/genetic-analyst/services.js
  src/router/routes/geneticAnalyst.js
  src/store/substrate/index.js
  src/views/Dashboard/GeneticAnalyst/Services/index.vue
  tests/unit/views/Dashboard/GeneticAnalyst/Services/index.spec.js
Labels: Feature, Test

#13 [DBIO-2084] feat: handle general error from API
  src/common/lib/api/index.js
  src/views/Dashboard/GeneticAnalyst/Layout.vue
Labels: Feature

#16 feat: git hooks
  .maintain/install-hooks.sh
  package.json
  tests/unit/crypt-worker.mock.js
  tests/unit/ipfs-worker.mock.js
  tests/unit/views/Dashboard/GeneticAnalyst/Orders/details.spec.js
  tests/unit/views/Dashboard/GeneticAnalyst/layout.spec.js
Labels: CI, Test, enhancement

#17 [DBIO-2084] fix: update single line condition & watch query
  src/common/lib/api/index.js
  src/views/Dashboard/GeneticAnalyst/Layout.vue
Labels: bug

#19 [DBIO-2224] ci: add new env
  .env-example
  .github/workflows/builder.yml
Labels: CI

#22 tests: full unit test example
  src/views/Dashboard/GeneticAnalyst/Services/index.vue
  tests/unit/views/Dashboard/GeneticAnalyst/Services/index.mock.js
  tests/unit/views/Dashboard/GeneticAnalyst/Services/index.spec.js
Labels: Test

#23 fix: fix debio balance on navbar
  package-lock.json
  src/common/components/Navbar.vue
Labels: Fix
