Repository debionetwork/debio-genetic-analyst-ui, pull requests merged in 2022-11, with the labels that each got.

#158 feat: remove USN
  src/common/components/Service/AddService.vue
  src/common/lib/api/customer/debio-balance.js
  src/views/Dashboard/GeneticAnalyst/Registration/AddService.vue
Labels: Feature

#165 feat: add conversion
  src/common/components/Service/AddService.vue
Labels: Feature

#167 feat: add copywriting below service price
  src/common/components/Service/AddService.vue
Labels: Feature

#170 fix: remove unused env
  .env-template
  .maintain/docker/entrypoint.sh
  src/store/auth.js
Labels: CI, Fix

#171 fix : error in entrypoint
  .maintain/docker/entrypoint.sh
Labels: CI
