Repository debionetwork/debio-genetic-analyst-ui, pull requests merged in 2022-06, with the labels that each got.

#42 fix: typo and update polkadot provider package
  package.json
  src/views/Dashboard/GeneticAnalyst/Orders/Details.vue
Labels: Fix, bug

#43 ci: use wlif for gcr auth
  .github/workflows/analyzer.yml
  .github/workflows/builder.yml
  .github/workflows/deployer.yml
  .github/workflows/tester.yml
Labels: CI

#44 ci: fix create draft release
  .github/workflows/builder.yml
Labels: CI

#38 refactor: Add required file document
  src/common/lib/pinata-proxy.js
Labels: enhancement, refactor

#39 feat: add linkedin profile link
  src/common/constants/error-messages.js
  src/common/constants/rules.js
  src/views/Dashboard/GeneticAnalyst/Account/index.vue
Labels: Feature, Fix

#40 fix: defect GA regist
  src/common/components/Account/InformationForm.vue
  src/common/components/Dialog/CertificateDialog.vue
  src/common/components/Dialog/InsufficientBalanceDialog.vue
  src/common/components/Dialog/StakeDialog.vue
  src/common/components/Service/AddService.vue
  src/common/lib/route-guard.js
  src/router/routes/registration.js
  src/views/Dashboard/GeneticAnalyst/Registration/AddService.vue
  src/views/Dashboard/GeneticAnalyst/Services/AddService.vue
  src/views/Dashboard/GeneticAnalyst/Services/EditService.vue
  tests/unit/common/components/Service/AddService.spec.js
  tests/unit/views/Dashboard/GeneticAnalyst/Registration/AccountInformation.spec.js
  tests/unit/views/Dashboard/GeneticAnalyst/Registration/AddService.spec.js
  tests/unit/views/Dashboard/GeneticAnalyst/Services/AddService.spec.js
  tests/unit/views/Dashboard/GeneticAnalyst/Services/EditService.spec.js
Labels: Fix, bug, tests

#46 fix: wording and styling on generate accout
  src/views/LandingPage/GenerateAccount/GenerateMnemonic/index.vue
  src/views/LandingPage/GenerateAccount/VerifyMnemonic/index.vue
  src/views/LandingPage/GenerateAccount/index.vue
  src/views/LandingPage/LandingPagePopUp.vue
  src/views/LandingPage/Layout.vue
Labels: Fix

#47 refactor: Upload document flow
  src/views/Dashboard/GeneticAnalyst/Orders/Details.vue
Labels: Improvement

#48 feat: add linkedin field on regist page
  src/common/components/Account/InformationForm.vue
  src/views/Dashboard/GeneticAnalyst/Registration/AccountInformation.vue
Labels: Feature

#45 feat : Active order validation
  src/common/components/Dialog/WarningDialog.vue
  src/views/Dashboard/GeneticAnalyst/Account/index.vue
  src/views/Dashboard/GeneticAnalyst/Services/index.vue
  tests/unit/views/Dashboard/GeneticAnalyst/Services/index.spec.js
Labels: Feature, enhancement

#50 fix: format price & value
  src/common/components/Service/AddService.vue
  src/views/Dashboard/GeneticAnalyst/Services/EditService.vue
Labels: Fix

#52 feat: Add file size description
  src/common/components/Account/InformationForm.vue
  src/common/components/Dialog/CertificateDialog.vue
  src/common/components/Service/AddService.vue
  src/common/lib/pinata-proxy.js
  src/views/Dashboard/GeneticAnalyst/Account/index.vue
  src/views/Dashboard/GeneticAnalyst/Orders/Details.vue
Labels: Improvement

#54 fix: GA download file
  src/views/Dashboard/GeneticAnalyst/Orders/Details.vue
Labels: Fix

#51 feat: add switch network to mainnet / testnet
  src/common/lib/metamask/index.js
  src/common/styles/mixins.sass
  src/views/Dashboard/GeneticAnalyst/Layout.vue
  src/views/LandingPage/GenerateAccount/index.vue
  src/views/LandingPage/LandingPagePopUp.vue
Labels: Fix

#53 refactor: remove /genetic-analyst path
  src/common/components/Navbar.vue
  src/router/routes/geneticAnalyst.js
Labels: refactor

#56 ci: add sleuth webhook
  .github/workflows/deployer.yml
Labels: CI

#58 fix: service price validation
  src/common/components/Service/AddService.vue
Labels: Fix

#57 fix: GA image and file size
  package-lock.json
  package.json
  src/views/Dashboard/GeneticAnalyst/Orders/Details.vue
Labels: Fix, enhancement

#59 feat: adjust wording on set/change password
  src/common/lib/route-guard.js
  src/router/routes/generateAccount.js
  src/views/LandingPage/GenerateAccount/RegistrationSuccessful.vue
  src/views/LandingPage/LandingPagePopUp.vue
  src/views/LandingPage/SignIn/ChangePassword.vue
  src/views/LandingPage/index.vue
  tests/unit/views/LandingPage/GenerateAccount/registration-successful.spec.js
Labels: Fix, bug

#61 fix: wrong routes on genetic-analyst login and registration
  src/common/lib/route-guard.js
  src/router/routes/geneticAnalyst.js
Labels: Fix
