Repository debionetwork/debio-genetic-analyst-ui, pull requests merged in 2022-12, with the labels that each got.

#174 fix: stake ga registration
  src/common/components/Dialog/StakeDialog.vue
Labels: Fix

#175 feat: init healt professional feature
  src/assets/genetic-analyst-icon.png
  src/assets/health-professional-icon.png
  src/common/components/Navbar.vue
  src/common/lib/route-guard.js
  src/router/routes/generate-account.js
  src/router/routes/genetic-analyst.js
  src/router/routes/health-professional.js
  src/router/routes/index.js
  src/router/routes/landing-page.js
  src/router/routes/registration.js
  src/router/routes/signIn.js
  src/views/Dashboard/HealthProfessional/Account/index.vue
  src/views/Dashboard/HealthProfessional/Home/index.vue
  src/views/Dashboard/HealthProfessional/Layout.vue
  src/views/LandingPage/GenerateAccount/RegistrationSuccessful.vue
  src/views/LandingPage/SelectRole/index.vue
  src/views/LandingPage/SignIn/index.vue
  src/views/NotFound.vue
Labels: Feature

#180 feat: add usdt token id
  .env-template
  .maintain/docker/entrypoint.sh
  src/common/components/Navbar.vue
  src/common/lib/polkadot-provider/query/octopus-assets.js
Labels: Feature

#182 feat: change payment from USDT to USDT.e
  src/common/components/Navbar.vue
  src/common/components/Service/AddService.vue
  src/common/lib/balance-format.js
  src/views/Dashboard/GeneticAnalyst/Registration/AddService.vue
  src/views/Dashboard/GeneticAnalyst/Services/AddService.vue
  src/views/Dashboard/GeneticAnalyst/Services/EditService.vue
  src/views/Dashboard/GeneticAnalyst/Services/index.vue
Labels: Feature

#187 fix: USDTE on Detail Order Page
  src/views/Dashboard/GeneticAnalyst/Orders/Details.vue
Labels: Fix

#181 feat: add dashboard and registration pages (ui-only)
  src/assets/health-professional-banner.svg
  src/common/components/Account/InformationForm.vue
  src/common/components/Dialog/RegistrationSentDialog.vue
  src/common/components/Dialog/SuccessDialogGeneral.vue
  src/common/components/HealthProfessionalBanner.vue
  src/router/routes/genetic-analyst.js
  src/router/routes/health-professional.js
  src/store/auth.js
  src/views/Dashboard/GeneticAnalyst/Registration/AccountInformation.vue
  src/views/Dashboard/HealthProfessional/Account/index.vue
  src/views/Dashboard/HealthProfessional/Home/index.vue
Labels: Feature

#190 fix: render USDTE on order list
  src/common/components/Orders/OrderList.vue
Labels: Fix

#122 chore(main): release 1.1.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease: pending

#200 feat: add install polkadot pop up
  src/common/components/Navbar.vue
  src/views/Dashboard/HealthProfessional/Home/index.vue
Labels: Feature

#199 feat: medical provider registration form enhancement
  src/common/components/Account/InformationForm.vue
  src/common/components/Account/dummySpecialization.json
  src/common/components/Orders/OrderList.vue
  src/views/Dashboard/GeneticAnalyst/Home/Unverified.vue
  src/views/Dashboard/HealthProfessional/Account/index.vue
  src/views/Dashboard/HealthProfessional/Home/index.vue
Labels: Feature

#204 feat: add tooltip on privacy setting
  src/common/components/Account/InformationForm.vue
Labels: Feature

#205 feat: connect to myriad page
  src/assets/connection-loading.svg
  src/assets/debio-logo-loading.svg
  src/assets/debio-to-myriad.svg
  src/assets/myriad-logo-loading.svg
  src/views/Dashboard/HealthProfessional/Home/index.vue
Labels: Feature

#206 fix: change connection loading from pop up to page
  src/assets/myriad-logo.png
  src/router/index.js
  src/views/Dashboard/HealthProfessional/ConnectingPage.vue
  src/views/Dashboard/HealthProfessional/Home/index.vue
Labels: Feature
