Repository debionetwork/debio-genetic-analyst-ui, pull requests merged in 2022-04, with the labels that each got.

#24 feat: upgrade provider package
  package-lock.json
  package.json
  src/common/lib/polkadot-provider/command/genetic-analyst/orders.js
  src/common/lib/polkadot-provider/command/genetic-analyst/qualifications.js
  src/common/lib/polkadot-provider/command/genetic-analyst/services.js
  src/common/lib/polkadot-provider/query/genetic-analyst-qualifications.js
  src/common/lib/polkadot-provider/query/genetic-analyst/services.js
  src/views/Dashboard/GeneticAnalyst/Account/index.vue
  src/views/Dashboard/GeneticAnalyst/Orders/Details.vue
  src/views/Dashboard/GeneticAnalyst/Services/index.vue
  tests/unit/views/Dashboard/GeneticAnalyst/Services/index.spec.js
Labels: Feature, Fix

#20 fix: add validation on some form & fix popup edit certification
  src/common/constants/rules.js
  src/views/Dashboard/GeneticAnalyst/Account/index.vue
Labels: bug

#25 refactor : Update the pinata gateway link with ENV
  src/common/lib/pinata-proxy.js
Labels: Improvement

#27 ci: add new env
  .github/workflows/builder.yml
Labels: CI

#30 feat: add loading spinner on upload
  src/common/components/Orders/OrderList.vue
  src/common/lib/pinata-proxy.js
  src/store/genetic-data.js
  src/views/Dashboard/GeneticAnalyst/Home/index.vue
  src/views/Dashboard/GeneticAnalyst/Orders/Details.vue
  src/views/Dashboard/GeneticAnalyst/Orders/index.vue
Labels: Feature, Improvement

#28 fix: enhance GA account
  package.json
  src/common/lib/pinata-proxy.js
  src/views/Dashboard/GeneticAnalyst/Account/index.vue
Labels: Fix

#31 fix: GA orders lists
  src/common/components/Orders/OrderList.vue
  src/views/Dashboard/GeneticAnalyst/Orders/Details.vue
Labels: Fix

#32 fix: handle trackingId if return <none>
  src/common/components/Orders/OrderList.vue
  src/views/Dashboard/GeneticAnalyst/Home/index.vue
  src/views/Dashboard/GeneticAnalyst/Orders/index.vue
Labels: Fix
