Repository debionetwork/debio-genetic-analyst-ui, pull requests merged in 2022-08, with the labels that each got.

#83 chore: bump version to 1.0.6
  package-lock.json
  package.json
Labels: Feature

#84 chore: revise env-example
  .env-example
Labels: Feature

#85 feat: dynamic watch URL params via notification
  package-lock.json
  package.json
  src/views/Dashboard/GeneticAnalyst/Layout.vue
  src/views/Dashboard/GeneticAnalyst/Orders/Details.vue
  src/views/Dashboard/GeneticAnalyst/Registration/AddService.vue
  src/views/Dashboard/GeneticAnalyst/Services/EditService.vue
Labels: Feature, enhancement

#87 feat: Add block number on the notification data field
  src/store/substrate/index.js
  src/views/Dashboard/GeneticAnalyst/Layout.vue
  src/views/Dashboard/GeneticAnalyst/Orders/Details.vue
Labels: Fix, Improvement

#86 feat: add clear account when signout and change password
  src/common/components/Navbar.vue
  src/views/Dashboard/GeneticAnalyst/Layout.vue
  src/views/LandingPage/SignIn/ChangePassword.vue
Labels: Feature

#89 fix: clear account and bump version 1.0.7
  package-lock.json
  package.json
  src/common/components/Navbar.vue
  src/views/Dashboard/GeneticAnalyst/Layout.vue
  src/views/LandingPage/SignIn/ChangePassword.vue
Labels: Fix

#90 feat: Update polkadot-provider version
  package-lock.json
  package.json
Labels: enhancement

#91 fix: route guard check account status
  src/common/lib/route-guard.js
Labels: Fix

#88 refactor: remove metamask
  src/App.vue
  src/common/components/Account/InformationForm.vue
  src/common/components/Dialog/DeleteServiceDialog.vue
  src/common/components/Dialog/StakeDialog.vue
  src/common/components/Navbar.vue
  src/common/components/Orders/OrderList.vue
  src/common/lib/balance-format.js
  src/common/lib/metamask/escrow.js
  src/common/lib/metamask/index.js
  src/common/lib/metamask/mixins/README.md
  src/common/lib/metamask/mixins/metamaskServiceHandler.js
  src/common/lib/metamask/usdt/abi.json
  src/common/lib/metamask/usdt/index.js
  src/common/lib/metamask/wallet.js
  src/common/lib/wallet.js
  src/main.js
  src/store/ethereum/index.js
  src/store/index.js
  src/store/metamask/contracts/abi/ERC20Interface.json
  src/store/metamask/contracts/abi/Escrow.json
  src/store/metamask/contracts/index.js
  src/store/web3Store/index.js
  src/views/Dashboard/GeneticAnalyst/Account/index.vue
  src/views/Dashboard/GeneticAnalyst/Home/Unverified.vue
  src/views/Dashboard/GeneticAnalyst/Layout.vue
  src/views/Dashboard/GeneticAnalyst/Orders/Details.vue
  src/views/Dashboard/GeneticAnalyst/Registration/AddService.vue
  src/views/Dashboard/GeneticAnalyst/Services/AddService.vue
  src/views/Dashboard/GeneticAnalyst/Services/EditService.vue
  src/views/Dashboard/GeneticAnalyst/Services/index.vue
Labels: Improvement, refactor

#93 fix: typo subtitle banner dashboard
  src/views/Dashboard/GeneticAnalyst/Home/Unverified.vue
Labels: Fix, bug
