Repository debionetwork/debio-genetic-analyst-ui, pull requests merged in 2022-07, with the labels that each got.

#60 fix: unstake GA & set availability
  .browserslistrc
  package-lock.json
  package.json
  src/common/components/Account/InformationForm.vue
  src/common/components/Dialog/DeleteServiceDialog.vue
  src/common/components/Dialog/StakeDialog.vue
  src/common/lib/polkadot-provider/command/genetic-analyst/index.js
  src/common/lib/polkadot-provider/command/genetic-analyst/qualification.js
  src/common/lib/polkadot-provider/command/genetic-analyst/services.js
  src/views/Dashboard/GeneticAnalyst/Account/index.vue
  vue.config.js
Labels: Fix

#64 fix: Event not show
  src/store/substrate/index.js
Labels: Fix

#65 ci: improve github workflows
  .github/workflows/builder.yml
  .github/workflows/create-tags.yml
  .github/workflows/deployer.yml
  .github/workflows/release.yml
Labels: CI

#66 ci: update version & formatting
  .github/workflows/analyzer.yml
  .github/workflows/builder.yml
  .github/workflows/create-tags.yml
  .github/workflows/deployer.yml
  .github/workflows/release.yml
  .github/workflows/update-version.yml
Labels: CI

#68 fix: GA upload result
  src/views/Dashboard/GeneticAnalyst/Orders/Details.vue
Labels: Fix

#69 fix: DoB convert to millisecond
  src/views/Dashboard/GeneticAnalyst/Registration/AccountInformation.vue
Labels: Fix

#71 ci: fix action permission
  .github/workflows/create-tags.yml
Labels: CI

#73 ci: revert "fix action permission"
  .github/workflows/create-tags.yml
Labels: CI

#74 ci: revert "fix create tags & release"
  .github/workflows/create-tags.yml
  .github/workflows/release.yml
Labels: CI

#75 ci: revert "update version & formatting"
  .github/workflows/analyzer.yml
  .github/workflows/builder.yml
  .github/workflows/create-tags.yml
  .github/workflows/deployer.yml
  .github/workflows/release.yml
  .github/workflows/update-version.yml
Labels: CI

#76 ci: revert "improve github workflows"
  .github/workflows/builder.yml
  .github/workflows/create-tags.yml
  .github/workflows/deployer.yml
  .github/workflows/release.yml
Labels: CI

#72 feat: display app version
  package.json
  src/common/components/NavigationDrawer.vue
Labels: Feature, enhancement

#77 ci: added app version
  .env-example
  .github/workflows/builder.yml
Labels: CI

#78 ci: get package version
  .github/workflows/builder.yml
Labels: CI

#79 chore: bump version to 1.0.5
  package.json
Labels: Feature

#80 fix: package.json
  package-lock.json
  package.json
Labels: Fix

#81 fix: remove switch network
  src/views/Dashboard/GeneticAnalyst/Layout.vue
Labels: Fix
