Repository debionetwork/debio-genetic-analyst-ui, pull requests merged in 2022-09, with the labels that each got.

#94 fix: change from Expected to Maximum
  src/common/components/Service/AddService.vue
  src/views/Dashboard/GeneticAnalyst/Orders/Details.vue
Labels: Fix

#92 feat: Implement backend notification
  src/common/components/Navbar.vue
  src/common/lib/api/customer/index.js
  src/common/lib/api/customer/notification.js
  src/common/lib/notification.js
  src/store/substrate/index.js
  src/views/Dashboard/GeneticAnalyst/Layout.vue
Labels: Improvement

#95 feat: runtime env variable
  .dockerignore
  .env-template
  .maintain/docker/Dockerfile
  .maintain/docker/entrypoint.sh
  .maintain/docker/nginx/nginx.conf
  docs/metamask-wallet-creation-steps.md
  docs/test-wallet.md
  public/index.html
  src/common/components/NavigationDrawer.vue
  src/common/lib/api/index.js
  src/common/lib/pinata-proxy.js
  src/common/lib/utils/env.js
  src/main.js
  src/router/index.js
  src/store/auth.js
  src/store/wallet.js
  src/views/LandingPage/GenerateAccount/SetPassword.vue
  src/views/LandingPage/SignIn/ChangePassword.vue
Labels: Feature

#96 fix: linter error
  src/common/lib/utils/env.js
Labels: Fix, bug

#97 ci: move registry to docker hub
  .github/workflows/builder.yml
Labels: CI

#98 fix: error on staking GA
  src/common/components/Dialog/StakeDialog.vue
Labels: Fix, bug

#100 ci: fix docker entrypoint sed delimiter
  .maintain/docker/entrypoint.sh
Labels: CI

#101 fix: fetch notification
  src/store/substrate/index.js
  src/views/Dashboard/GeneticAnalyst/Layout.vue
Labels: Fix

#102 feat: add fmtReferenceFromHex to string-format file
  src/common/lib/notification.js
  src/common/lib/string-format.js
Labels: enhancement

#103 feat: add USN and USDT on currency list
  src/common/components/Service/AddService.vue
Labels: Feature

#104 ci: improvement
  .dockerignore
  .github/CODEOWNERS
  .github/pull_request_template.md
  .github/workflows/analyzer.yaml
  .github/workflows/analyzer.yml
  .github/workflows/builder.yaml
  .github/workflows/builder.yml
  .github/workflows/deployer.yml
  .github/workflows/mlc_config.json
  .github/workflows/rcb_config.json
  .github/workflows/releaser.yaml
  .github/workflows/tester.yaml
  .github/workflows/tester.yml
  .maintain/docker/Dockerfile
  .maintain/docker/docker-compose.yml
  .maintain/docker/entrypoint.sh
  README.md
  package.json
Labels: CI

#105 ci: bump scorecard to v2
  .github/dependabot.yaml
  .github/pull_request_template.md
  .github/workflows/analyzer.yaml
Labels: CI

#109 ci: fix scorecard version
  .github/workflows/analyzer.yaml
Labels: CI

#110 ci: fixed docker entrypoint
  .maintain/docker/entrypoint.sh
Labels: CI

#111 ci: fixed release auth workflow
  .github/workflows/releaser.yaml
Labels: CI

#113 ci: fixed docker builder
  .github/pull_request_template.md
  .github/workflows/analyzer.yaml
  .github/workflows/builder.yaml
  .github/workflows/mlc_config.json
Labels: CI

#114 feat: add usn & usdt on wallet
  src/assets/debio-logo.svg
  src/assets/near-logo.svg
  src/assets/tether-logo.svg
  src/common/components/Navbar.vue
  src/common/lib/polkadot-provider/query/octopus-assets.js
Labels: Feature

#115 ci: cleanup ssh tunneling
  .github/workflows/deployer.yml
  .maintain/docker/entrypoint.sh
  README.md
Labels: CI
