Repository debionetwork/debio-genetic-analyst-ui, pull requests merged in 2023-02, with the labels that each got.

#230 feat: enhance mobile view
  src/common/lib/api/health-professional/myriad.js
  src/views/Dashboard/HealthProfessional/Home/index.vue
  src/views/NoAccessMobile.vue
Labels: Feature

#233 fix: registrahtion hp enhancement
  src/App.vue
  src/common/components/Account/InformationForm.vue
  src/common/components/Dialog/InsufficientBalanceDialog.vue
  src/common/lib/api/health-professional/index.js
  src/common/lib/api/health-professional/myriad.js
  src/common/lib/api/health-professional/registration-email.js
  src/views/Dashboard/HealthProfessional/Account/index.vue
  src/views/Dashboard/HealthProfessional/Home/index.vue
  src/views/Dashboard/HealthProfessional/Layout.vue
  src/views/NoAccessMobile.vue
Labels: Feature, Fix

#234 fix: hp dashboard
  src/common/components/Account/InformationForm.vue
  src/views/Dashboard/HealthProfessional/Home/index.vue
Labels: Fix

#235 feat: direct to myriad and fix fetch post data
  .env-template
  .maintain/docker/entrypoint.sh
  src/common/lib/api/health-professional/myriad.js
  src/views/Dashboard/HealthProfessional/Home/index.vue
Labels: Feature, Fix

#242 fix: some wordings and fetch unlocked content
  src/views/Dashboard/HealthProfessional/Home/index.vue
Labels: Fix

#244 fix: change amount to boolean on unlocked content column
  src/views/Dashboard/HealthProfessional/Home/index.vue
Labels: Fix

#245 fix: adjust api myriadContents
  src/common/lib/api/health-professional/myriad.js
Labels: Fix

#246 fix: adjust api myriad contents
  src/common/lib/api/health-professional/myriad.js
Labels: Fix

#201 chore(main): release 1.2.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease: pending

#247 feat: add API for get health professional roles
  src/common/components/Account/InformationForm.vue
  src/common/lib/api/health-professional/specialization.js
Labels: Feature

#248 chore(main): release 1.3.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease: pending

#250 fix: handle short nonce
  src/views/Dashboard/HealthProfessional/Account/index.vue
Labels: Fix

#251 chore(main): release 1.3.1
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease: pending
